version: '3.1'
services:
  nginx:
    image: nginx:1.13.7
    container_name: nginx-babel
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - babel
    ports:
      - 80:80

networks:
  babel:
    external:
      name: babel